"""Content of the workbook's 'Read Me' sheet. Regenerated by update_param_reference.py so the
counts, SONiC commit and file names stay in sync with the data."""
import collections
from openpyxl.styles import Font, Alignment

H = "H"   # heading marker


def lines(stats):
    s = stats
    return [
        (H, "CMIS 5.3 Parameter Reference"),
        "Machine- and human-readable map of every register field in OIF-CMIS-05.3 Section 8 (Memory Map).",
        "Source: OIF-CMIS-05.3, Common Management Interface Specification rev 5.3 (4 Sept 2024) — https://www.oiforum.com/wp-content/uploads/OIF-CMIS-05.3.pdf",
        "The specification is authoritative. Use this workbook to search, filter and generate code or tests; verify timing- or safety-critical details against the PDF.",
        "",
        (H, "SHEETS"),
        f"Memory Map (Sec 8) — {s['rows']} rows: {s['fields']} fields and {s['reserved']} reserved regions, one row per field per location, in memory order.",
        f"CDB Commands — {s['cdb']} CDB commands defined in Section 9: ID, title, group, requirement, section and the spec table holding each command's payload layout. Payload fields are not included yet.",
        "CMIS_5.3_Memory_Map.csv and CMIS_5.3_CDB_Commands.csv (same folder) are plain-text copies of the two data sheets, regenerated with them; prefer them for code, agents and diffs.",
        "Column meanings are in the comment on each header cell (hover in Excel; agents: read the cell comments).",
        "",
        (H, "CONVENTIONS (Memory Map)"),
        "Page: 0xNN for Upper Memory pages. Blank = Lower Memory (bytes 0-127). 0x00 = Upper Page 00h.",
        "Byte: first byte address in decimal, as the spec prints it. Byte Length: number of bytes.",
        "Mask Bytes: one 0x-hex mask per byte, increasing address order. Blank = all bits of every byte.",
        "Bank Scope: blank = unbanked; otherwise Lane-banked, Application-banked (page 1Ch) or CDB-instance (pages 9Fh-AFh).",
        "Value Type: blank = Reserved region (CMIS Name 'Reserved').",
        "Shading: Reserved rows are light gray (5%). In field rows, darker gray (15%) marks meaningful blanks in Page, Mask Bytes, Bank Scope, Value Type, Access, Behavior and Requirement (Requirement blank = the spec states none).",
        "Key ID: unique row key = CMIS Name; when a name repeats, suffixes are added in order: .<page> (2-digit hex + 'h', Lower Memory = 'Lwr') if the repeats span pages, then .<byte> (decimal), then .<mask> (0x hex). Example: PageChecksum.01h, Reserved.01h.158.0xF8. Keys can change if a later CMIS revision adds a duplicate name.",
        "Per-lane arrays printed with <n> in the spec (e.g. GridSpacingTx<n>, bytes 128-135) are expanded to one row per lane (GridSpacingTx1 ... Tx8).",
        "Condition: set for page 14h rows whose meaning depends on DiagnosticsSelector (e.g. DiagnosticsSelector=01h); those rows share bytes by design.",
        "DateCode (00h:182-189) is listed both as the whole field and as its Year/Month/DayOfMonth/LotCode parts.",
        "Access/Behavior/Requirement come from the spec's Type cell (RO/RW/WO/RWW, COR = ClearOnRead, SC = SelfClearing; Rqd/Opt/Cnd/Adv). Reserved rows carry no Requirement. Page 14h diagnostics data (Table 8-129) has no Type column and is marked RO.",
        "Conversion: engineering value = raw (per Value Type and Byte Order) x Scale, in Unit — e.g. TempMonValue s16 x 0.00390625 = degC; OpticalPowerTx<n> u16 x 0.1 = uW; HostSideSNRLane<n> u16 little-endian x 0.00390625 = dB. Conversion Note covers conditional or multi-register rules (Aux monitors, LaserBias scaling factor, length multipliers, F16). Unit/Scale are parsed from the spec text; multi-byte numbers are big-endian unless the spec says little-endian.",
        "Value Type is normalized (bool, u8, u16, s16, f16, u32, bitfieldN, enumN, ascii[N] ...); 'unspecified' means the width alone does not determine it — read the Description.",
        "",
        (H, "SCOPE"),
        "CDB (Section 9): the command list is included (CDB Commands sheet); CMD/REPLY payload field layouts are not yet — use each command's Detail Table in the spec. Reserved command IDs are not listed.",
        "CDB IDs 0050h, 0051h and 0281h have detail tables but are not listed in their overview tables (which mark those IDs reserved); they are included with a Note and no Requirement.",
        "Included: every Section 8 table that defines fixed addresses (Lower Memory and pages 00h-2Fh, 9Fh).",
        "Excluded: page-overview summary tables (they duplicate the detail tables; only PageChecksum of pages 00h-02h is taken from them), "
        "format templates (Tables 8-22, 8-163, 8-169, 8-173) and page-range tables (8-168, 8-171, 8-172 VDM pages 20h-2Bh; 8-180 CDB message body; 8-181 EPL pages A0h-AFh).",
        "",
        (H, "HOW IT IS BUILT"),
        "Rows are extracted from the PDF's table grid with pdfplumber (not line-by-line text), so merged Type cells, byte ranges that wrap across lines and multi-page tables are read correctly.",
        f"Scripts and inputs are in the tools folder next to this workbook; tools/README.md lists the commands. Hand corrections: tools/data/corrections.csv ({s['errata']} rows), keyed by page/byte/mask with an expected-name guard, applied on every rebuild.",
        "Each rebuild lists what changed versus the previous version, and whether every correction still applied, in Memory_Map_Rebuild_Changes.xlsx.",
        "",
        (H, "VALIDATION"),
        f"SONiC Cross-check / SONiC Field — bit-level comparison with SONiC sonic-platform-common CmisMemMap (bank 0, commit {s['sonic_sha'][:12]}). "
        f"Results: {s['sonic']}. 'Page not in SONiC' and 'Not in SONiC' are coverage gaps, not errors. SONiC is a behavioral reference, not a compliance oracle.",
        "",
        (H, "RELATED FILES (same folder)"),
        "OIF-CMIS-05.3.pdf — the specification used for extraction.",
        "",
        (H, "KNOWN LIMITATIONS"),
        "Some Requirement cells are blank because the spec prints none for that row (e.g. VDM flags, page 14h data).",
        "Value Type for rows added in the re-extraction is inferred from width and the description's type token.",
    ]


def write(ws, stats):
    ws.delete_rows(1, ws.max_row)
    for i, ln in enumerate(lines(stats), start=1):
        head = isinstance(ln, tuple)
        c = ws.cell(i, 1, ln[1] if head else (ln or None))
        c.font = Font(bold=head, size=12 if i == 1 else 10)
        c.alignment = Alignment(wrap_text=True, vertical="top")
    ws.column_dimensions["A"].width = 120
    ws.sheet_view.showGridLines = False
